---
name: Megalinter Full Lint

on:
  pull_request:
    branches:
      - main
    # if any of the linter workflows have changed (e.g. dependabot PR), lint the full code base
    # to ensure we do not accumulate unknown linter tech-debt
    paths:
      - .github/workflows/megalinter*.yml
      - .mega-linter.yml
      - .github/linters/**

permissions: {}

jobs:
  lint:
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write
    uses: ./.github/workflows/megalinter.yml
    with:
      full: true
