name: Promote Candidate Release

on:
  release:
    types: [published]

permissions: {}

jobs:
  sbom:
    name: Bill of Materials
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate SBOM
        uses: advanced-security/sbom-generator-action@6fe43abf522b2e7a19bc769aec1e6c848614b517 # v0.0.2
        id: sbom
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Attach SBOM
        run: gh release upload --clobber "${{ github.event.release.tag_name }}" "${{ steps.sbom.outputs.fileName }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  promote-jfrog-prod:
    name: Promote to Jfrog's Prod environment
    uses: BeyondTrust/workflows/.github/workflows/promote-jfrog-release-bundle.yaml@51e9f52f8446a28edae9c7277ce1a612b86570ea # v4.13.1
    permissions:
      pull-requests: write
    secrets: inherit

  publish-terraform-registry:
    name: Publish to Terraform Registry
    runs-on: ubuntu-latest
    needs: [promote-jfrog-prod]
    permissions:
      contents: write
    env:
      JF_ENV_1: ${{ secrets.ARTIFACTORY_DEPLOYER }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup JFrog
        uses: beyondtrust/setup-jfrog-cli@26d84636538c322aed2f822374a0b976b23caa81 # v2.4.3

      - name: Extract version
        id: info
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Download provider artifacts from Artifactory
        run: |
          jf rt download \
            "eng-tf-provider-prod-local/beyondtrust/beyondtrust/${{ steps.info.outputs.version }}/terraform-provider-beyondtrust_*" \
            dist/ --flat=true

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Sign SHA256SUMS
        run: |
          VERSION="${{ steps.info.outputs.version }}"
          gpg --batch --yes --detach-sign \
            --local-user "${{ steps.import_gpg.outputs.fingerprint }}" \
            --output "dist/terraform-provider-beyondtrust_${VERSION}_SHA256SUMS.sig" \
            "dist/terraform-provider-beyondtrust_${VERSION}_SHA256SUMS"

      - name: Upload artifacts to GitHub release
        run: gh release upload --clobber "${{ github.event.release.tag_name }}" dist/terraform-provider-beyondtrust_*
        env:
          GITHUB_TOKEN: ${{ github.token }}
